import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import {getDatabase,ref,get,onValue,onDisconnect,runTransaction,set} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js';
import {firebaseConfig} from './firebase-config.js';
import {initial,move} from './engine.mjs?v=1.0.1';
import {unlockSound,soundEnabled,toggleSound,playShot,stopCelebration,announceSoundReady} from './sounds.js?v=1.3';
const db=getDatabase(initializeApp(firebaseConfig)),root=document.querySelector('#app'),tv=document.body.classList.contains('tv');
const colors=['#ff9700','#20aaff','#ff1556','#18d978','#b18aff','#ffe05c'];
let room='',data=null,multiplier=1,busy=false,timer=null,count=2,mode=501,connected=false,tvSoundReady=false,observedRoom=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rr=()=>ref(db,`rooms/${room}`);
function message(s){const el=document.querySelector('#message');if(el)el.textContent=s;}
function shots(g){return `<div class="shots">${[0,1,2].map(i=>`<div class="shot ${g.shots?.[i]?'filled':''}"><span>${esc(g.shots?.[i]?.label||i+1)}</span></div>`).join('')}</div>`;}
function watch(){onValue(ref(db,'.info/connected'),snap=>{connected=snap.val()===true;if(connected){const key=tv?'tvOnline':'remoteOnline';set(ref(db,`rooms/${room}/${key}`),true).catch(()=>{});onDisconnect(ref(db,`rooms/${room}/${key}`)).set(false);}if(data?.game)render();});onValue(rr(),snap=>{const previous=data;data=snap.val();if(!data)return;if(tv&&observedRoom)handleTVAudio(previous,data);observedRoom=true;multiplier=1;if(data.game)render();else if(tv)waiting();else if(!document.querySelector('#setup'))setup();});}
function waiting(){root.innerHTML=`<header><b>DART X01</b><span>101 · 301 · 501</span>${tvSoundButton()}</header><div class="waiting"><h1>Telefon kumandasını bağla</h1><div class="room">${room}</div><p>Telefonda remote.html sayfasını aç ve bu kodu gir.</p><p>${data?.remoteOnline?'Telefon bağlandı · Oyun hazırlanıyor':'Telefon bekleniyor'}</p></div>`;}
function setup(){root.innerHTML=`<section id="setup"><header><b>ODA ${room}</b><span>X01</span></header><h2>Kaç oyuncu?</h2><div class="grid counts">${[2,3,4,5,6].map(n=>`<button data-count="${n}" class="${n===count?'selected':''}">${n}</button>`).join('')}</div><h2>Oyuncu isimleri</h2><div id="names"></div><h2>Oyun seç</h2><div class="grid modes">${[101,301,501].map(n=>`<button data-mode="${n}" class="${n===mode?'selected':''}">${n}</button>`).join('')}</div><button id="start" class="start">OYUNU BAŞLAT</button><p id="message" role="status"></p></section>`;names();root.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{const values=[...root.querySelectorAll('#names input')].map(x=>x.value);count=+b.dataset.count;root.querySelectorAll('[data-count]').forEach(x=>x.classList.toggle('selected',x===b));names(values);});root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=+b.dataset.mode;root.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));});document.querySelector('#start').onclick=async()=>{const values=[...root.querySelectorAll('#names input')].map((x,i)=>x.value.trim()||`Oyuncu ${i+1}`);try{await runTransaction(rr(),r=>r&&!r.game?{...r,game:initial(values,mode),history:[]}:undefined);}catch(e){message('Oyun başlatılamadı: '+e.message);}};}
function names(values=[]){document.querySelector('#names').innerHTML=Array.from({length:count},(_,i)=>`<input maxlength="28" aria-label="Oyuncu ${i+1}" placeholder="Oyuncu ${i+1}" value="${esc(values[i]||'')}">`).join('');}
function render(){const g=data.game,p=g.players[g.active],color=colors[g.active],win=g.winner!==null&&g.winner!==undefined;root.style.setProperty('--color',color);if(tv){root.innerHTML=`<header><b>DART X01 · ${g.mode}</b><span>TUR ${g.round} / ∞</span><span>ODA ${room} · ${connected&&data.remoteOnline?'Bağlı':'Telefon bağlantısı bekleniyor'}</span>${tvSoundButton()}</header><div class="players" style="--count:${g.players.length}">${g.players.map((p,i)=>`<div class="player ${i===g.active?'current':''}" style="--color:${colors[i]}"><strong>${esc(p.name)}</strong><b>${p.score}</b></div>`).join('')}</div><div class="stage">${win?`<div class="winner">🏆 ${esc(g.players[g.winner].name)}<br>KAZANDI</div><div class="big-score">0</div>`:`<div class="banner">${g.bust?'BUST · TUR İPTAL':`SENİN SIRAN · ${esc(p.name)}`}</div><div class="big-score">${p.score}</div>`}${shots(g)}<div class="total">TOPLAM ${g.shots?.reduce((s,x)=>s+x.value,0)||0}${g.bust?' · İPTAL':''}</div></div>`;return;}
root.innerHTML=`<header><b>ODA ${room} · ${g.mode}</b><span>TUR ${g.round}</span><span>${connected&&data.tvOnline?'Bağlı':'Bağlantı bekleniyor'}</span></header><div class="active"><strong>${esc(win?g.players[g.winner].name:p.name)}</strong><b>${p.score}</b></div>${shots(g)}<div class="grid double"><button data-m="2">DOUBLE</button><button data-m="3">TRIPLE</button></div><div class="grid numbers">${Array.from({length:20},(_,i)=>`<button data-n="${20-i}">${20-i}</button>`).join('')}</div><div class="grid bulls"><button data-b="25">BULL</button><button data-b="50">BULL'S EYE</button></div><div class="grid actions"><button id="miss">ISKA</button><button id="undo">GERİ</button><button id="skip">TURU GEÇ</button></div><p id="message" class="notice" role="status">${win?'🏆 KAZANDI':g.bust?'BUST · Skor turun başına döndü':g.pending?'Sonraki oyuncuya geçiliyor…':''}</p>${win?'<button id="new" class="start">YENİ OYUN</button>':''}`;
root.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{multiplier=multiplier===+b.dataset.m?1:+b.dataset.m;root.querySelectorAll('[data-m]').forEach(x=>{x.classList.toggle('selected',+x.dataset.m===multiplier);x.setAttribute('aria-pressed',String(+x.dataset.m===multiplier));});});root.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{const n=+b.dataset.n,m=multiplier;multiplier=1;act({type:'shot',value:n*m,label:`${['','S','D','T'][m]}${n}`});});root.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>{multiplier=1;act({type:'shot',value:+b.dataset.b,label:+b.dataset.b===25?'BULL':"BULL'S EYE"});});document.querySelector('#miss').onclick=()=>act({type:'shot',value:0,label:'ISKA'});document.querySelector('#skip').onclick=()=>act({type:'skip'});document.querySelector('#undo').onclick=()=>act({type:'undo'});if(win)document.querySelector('#new').onclick=()=>act({type:'new'});
root.querySelectorAll('button').forEach(b=>b.disabled=(busy||!connected||(win&&b.id!=='undo'&&b.id!=='new')||(!!g.pending&&b.id!=='undo')));clearTimeout(timer);if(g.pending&&connected)timer=setTimeout(()=>act({type:'advance'}),Math.max(0,g.pending-Date.now())+30);
}
async function act(action){if(busy||!connected)return;if(action.type==='shot'&&(data?.game?.winner!=null||data?.game?.pending))return;const soundId=`${Date.now()}-${Math.random().toString(36).slice(2)}`;busy=true;multiplier=1;render();try{await runTransaction(rr(),r=>{if(!r?.game)return;const hist=r.history||[];if(action.type==='new'){return {...r,game:null,history:[],soundEvent:null};}if(action.type==='undo'){if(!hist.length)return;const game=hist.pop();if(game.pending)game.pending=Date.now()+900;return {...r,game,history:hist,soundEvent:null};}const before=r.game,after=move(before,action);if(JSON.stringify(before)===JSON.stringify(after))return;if(action.type!=='advance'){hist.push(before);if(hist.length>150)hist.shift();}return {...r,game:after,history:hist,...(action.type==='shot'?{soundEvent:{id:soundId,label:action.label,bust:!!after.bust,won:after.winner!=null}}:{})};});}catch(e){message('İşlem kaydedilemedi: '+e.message);}finally{busy=false;if(data?.game)render();}}
async function initTV(){try{for(let i=0;i<40;i++){room=String(Math.floor(1000+Math.random()*9000));const result=await runTransaction(rr(),r=>r===null?{gameType:'x01',createdAt:Date.now(),tvOnline:true}:undefined);if(result.committed){waiting();watch();return;}}throw Error('Boş oda oluşturulamadı');}catch(e){root.textContent='Bağlantı kurulamadı: '+e.message;}}
async function join(){const code=document.querySelector('#code').value.trim();if(!/^\d{4}$/.test(code)){message('Dört haneli kodu gir.');return;}document.querySelector('#join').disabled=true;try{room=code;const s=await get(rr());if(!s.exists()||s.val().gameType!=='x01')throw Error('Bu kodla bir X01 odası bulunamadı');data=s.val();watch();}catch(e){message(e.message);document.querySelector('#join').disabled=false;}}
if(tv)initTV();else{document.querySelector('#join').onclick=join;document.querySelector('#code').onkeydown=e=>{if(e.key==='Enter')join();};const c=new URLSearchParams(location.search).get('room');if(c){document.querySelector('#code').value=c;join();}}

function tvSoundButton(){return `<button id="tv-sound" type="button" aria-pressed="${tvSoundReady&&soundEnabled()}" style="padding:8px 16px">${!tvSoundReady?'🔊 SESİ AÇ':soundEnabled()?'🔊 SES AÇIK':'🔇 SES KAPALI'}</button>`;}
function handleTVAudio(previous,next){
  if(!tvSoundReady||!soundEnabled())return;
  if(previous?.game?.winner!=null&&next.game?.winner==null)stopCelebration();
  const event=next.soundEvent;
  if(!event||event.id===previous?.soundEvent?.id)return;
  playShot({label:event.label},{bust:event.bust,winner:event.won?0:null});
}
root.addEventListener('click',event=>{
  if(!tv||!event.target.closest('#tv-sound'))return;
  if(!tvSoundReady){if(!soundEnabled())toggleSound();else{unlockSound();playShot({label:'S20'},{});}tvSoundReady=true;announceSoundReady();}
  else toggleSound();
  if(data?.game)render();else waiting();
  document.querySelector('#tv-sound')?.focus();
});
